apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flyteadmin
  namespace: flyte
rules:
  - apiGroups:
      - ""
      - flyte.lyft.com
      - rbac.authorization.k8s.io
    resources:
      - configmaps
      - flyteworkflows
      - namespaces
      - pods
      - resourcequotas
      - roles
      - rolebindings
      - secrets
      - services
      - serviceaccounts
      - spark-role
    verbs:
      - '*'

