apiVersion: v1
data:
  admin.yaml: |
    admin:
      clientId: flytepropeller
      clientSecretLocation: /etc/secrets/client_secret
      endpoint: flyteadmin:81
      insecure: true
    event:
      capacity: 1000
      rate: 500
      type: admin
  db.yaml: |
    database:
      dbname: postgres
      host: postgres
      port: 5432
      username: postgres
  logger.yaml: |
    logger:
      level: 4
      show-source: true
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: flyte
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: flytescheduler
    helm.sh/chart: flyte-v0.1.10
  name: flyte-scheduler-config
  namespace: flyte

