apiVersion: v1
data:
  cluster_resources.yaml: |
    cluster_resources:
      templatePath: "/etc/flyte/clusterresource/templates"
      customData:
        - production:
            - projectQuotaCpu:
                value: "5"
            - projectQuotaMemory:
                value: "4000Mi"
        - staging:
            - projectQuotaCpu:
                value: "2"
            - projectQuotaMemory:
                value: "3000Mi"
        - development:
            - projectQuotaCpu:
                value: "4"
            - projectQuotaMemory:
                value: "3000Mi"
      refreshInterval: 1m
  db.yaml: |
    database:
      port: 5432
      username: postgres
      host: postgres
      dbname: postgres
      options: sslmode=disable
  domain.yaml: |
    domains:
      - id: development
        name: development
      - id: staging
        name: staging
      - id: production
        name: production
  logger.yaml: |
    logger:
      show-source: true
      level: 2
  server.yaml: |
    server:
      httpPort: 8088
      grpcPort: 8089
      security:
        # Controls whether to serve requests over SSL/TLS.
        secure: false
        # Controls whether to enforce authentication. Follow the guide in https://docs.flyte.org/ on how to setup authentication.
        useAuth: false
        allowCors: true
        allowedOrigins:
          # Accepting all domains for Sandbox installation
          - "*"
        allowedHeaders:
          - "Content-Type"
          - "flyte-authorization"
    auth:
      authorizedUris:
        # This should point at your public http Uri.
        - https://localhost:30081
        # This will be used by internal services in the same namespace as flyteadmin
        - http://flyteadmin:80
        # This will be used by internal services in the same cluster but different namespaces
        - http://flyteadmin.flyte.svc.cluster.local:80

      # Controls app authentication config
      appAuth:
        thirdPartyConfig:
          flyteClient:
            clientId: flytectl
            redirectUri: https://localhost:53593/callback
            scopes:
              - offline
              - all
      # Controls user authentication
      userAuth:
        openId:
          baseUrl: https://accounts.google.com
          scopes:
            - profile
            - openid
          clientId: 657465813211-6eog7ek7li5k7i7fvgv2921075063hpe.apps.googleusercontent.com
    flyteadmin:
      roleNameKey: "iam.amazonaws.com/role"
  storage.yaml: |+
    storage:
      type: minio
      connection:
        access-key: minio
        auth-type: accesskey
        secret-key: miniostorage
        disable-ssl: true
        endpoint: http://minio.flyte.svc.cluster.local:9000
        region: us-east-1
      container: "my-s3-bucket"

  task_resource_defaults.yaml: |
    task_resources:
      defaults:
        cpu: 100m
        memory: 200Mi
        storage: 5Mi
      limits:
        cpu: 2
        memory: 1Gi
        storage: 20Mi
        gpu: 1
kind: ConfigMap
metadata:
  name: flyte-admin-config-dbg8dt2dgb
  namespace: flyte

