apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: flyte
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - env:
            - name: MINIO_ACCESS_KEY
              value: minio
            - name: MINIO_SECRET_KEY
              value: miniostorage
            - name: MINIO_DEFAULT_BUCKETS
              value: my-s3-bucket
          image: ecr.flyte.org/bitnami/minio:2021.10.13-debian-10-r0
          name: minio
          ports:
            - containerPort: 9000
              name: minio
            - containerPort: 9001
              name: minio-console
          volumeMounts:
            - mountPath: /data
              name: minio-storage
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
        runAsUser: 1001
      volumes:
        - emptyDir: {}
          name: minio-storage

