apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flyte-pod-webhook
  name: flyte-pod-webhook
  namespace: flyte
spec:
  selector:
    matchLabels:
      app: flyte-pod-webhook
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"
      labels:
        app: flyte-pod-webhook
        app.kubernetes.io/name: flyte-pod-webhook
        app.kubernetes.io/version: 0.5.13
    spec:
      containers:
        - args:
            - webhook
            - --config
            - /etc/flyte/config/*.yaml
          command:
            - flytepropeller
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: cr.flyte.org/flyteorg/flytepropeller:v0.16.29
          imagePullPolicy: IfNotPresent
          name: webhook
          volumeMounts:
            - mountPath: /etc/secrets/user-info
              name: sample-secrets
              readOnly: true
            - mountPath: /etc/flyte/config
              name: config-volume
              readOnly: true
            - mountPath: /etc/webhook/certs
              name: webhook-certs
              readOnly: true
      initContainers:
        - args:
            - webhook
            - init-certs
            - --config
            - /etc/flyte/config/*.yaml
          command:
            - flytepropeller
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: cr.flyte.org/flyteorg/flytepropeller:v0.16.29
          imagePullPolicy: IfNotPresent
          name: generate-secrets
          volumeMounts:
            - mountPath: /etc/flyte/config
              name: config-volume
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: Always
        runAsUser: 1001
      serviceAccountName: flyte-pod-webhook
      volumes:
        - name: sample-secrets
          secret:
            secretName: user-info
        - configMap:
            name: flyte-propeller-config-g52db28fmc
          name: config-volume
        - name: webhook-certs
          secret:
            secretName: flyte-pod-webhook

