apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flytescheduler
  name: flytescheduler
  namespace: flyte
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flytescheduler
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"
      labels:
        app: flytescheduler
        app.kubernetes.io/name: flytescheduler
        app.kubernetes.io/version: 0.3.4
    spec:
      containers:
        - command:
            - flytescheduler
            - run
            - --config
            - /etc/flyte/config/*.yaml
          image: cr.flyte.org/flyteorg/flytescheduler:v0.6.49
          imagePullPolicy: IfNotPresent
          name: flytescheduler
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: 100Mi
              memory: 500Mi
            requests:
              cpu: 10m
              ephemeral-storage: 50Mi
              memory: 50Mi
          volumeMounts:
            - mountPath: /etc/secrets/
              name: auth
            - mountPath: /etc/flyte/config
              name: config-volume
            - mountPath: /etc/db
              name: db-pass
      initContainers:
        - command:
            - flytescheduler
            - precheck
            - --config
            - /etc/flyte/config/*.yaml
          image: cr.flyte.org/flyteorg/flytescheduler:v0.6.49
          imagePullPolicy: IfNotPresent
          name: flytescheduler-check
          volumeMounts:
            - mountPath: /etc/flyte/config
              name: config-volume
      serviceAccountName: flyteadmin
      volumes:
        - configMap:
            name: flyte-scheduler-config
          name: config-volume
        - name: db-pass
          secret:
            secretName: db-pass-9dgchhk2bm
        - name: auth
          secret:
            secretName: flyte-secret-auth

