apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flyteconsole
  name: flyteconsole
  namespace: flyte
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flyteconsole
  template:
    metadata:
      labels:
        app: flyteconsole
        app.kubernetes.io/name: flyteconsole
        app.kubernetes.io/version: 0.19.0
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: flyte-console-config
          image: cr.flyte.org/flyteorg/flyteconsole:v0.43.0
          name: flyteconsole
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /srv/flyte
              name: shared-data
      securityContext:
        fsGroupChangePolicy: Always
        runAsUser: 1000
      volumes:
        - emptyDir: {}
          name: shared-data

