apiVersion: batch/v1
kind: Job
metadata:
  name: contour-certgen-v1.13.1
  namespace: projectcontour
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: contour-certgen
    spec:
      containers:
        - command:
            - contour
            - certgen
            - --kube
            - --incluster
            - --overwrite
            - --secrets-format=compact
            - --namespace=$(CONTOUR_NAMESPACE)
          env:
            - name: CONTOUR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: docker.io/projectcontour/contour:v1.13.1
          imagePullPolicy: Always
          name: contour
      restartPolicy: Never
      securityContext:
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: contour-certgen
  ttlSecondsAfterFinished: 0

