apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: contour-certgen
  namespace: projectcontour
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - update

