apiVersion: v1
kind: Service
metadata:
  annotations:
    projectcontour.io/upstream-protocol.h2c: grpc
  name: flyte-pod-webhook
  namespace: flyte
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app: flyte-pod-webhook

