apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio-direct
  namespace: flyte
spec:
  ports:
    - nodePort: 30084
      port: 9000
      protocol: TCP
  selector:
    app: minio
  type: NodePort

