apiVersion: v1
kind: Service
metadata:
  annotations:
    contour.heptio.com/upstream-protocol.h2c: grpc
  name: datacatalog
  namespace: flyte
spec:
  ports:
    - name: http
      port: 88
      protocol: TCP
      targetPort: 8088
    - name: grpc
      port: 89
      protocol: TCP
      targetPort: 8089
  selector:
    app: datacatalog

