apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
  name: envoy
  namespace: projectcontour
spec:
  externalTrafficPolicy: Local
  ports:
    - name: http
      nodePort: 30081
      port: 80
      protocol: TCP
    - name: https
      port: 443
      protocol: TCP
  selector:
    app: envoy
  type: NodePort

