apiVersion: v1
kind: Service
metadata:
  name: contour
  namespace: projectcontour
spec:
  ports:
    - name: xds
      port: 8001
      protocol: TCP
      targetPort: 8001
  selector:
    app: contour
  type: ClusterIP

