apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres-direct
  namespace: flyte
spec:
  ports:
    - nodePort: 30083
      port: 5432
      protocol: TCP
  selector:
    app: postgres
  type: NodePort

