apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: flyte
spec:
  externalName: minio
  ports:
    - name: minio-api
      port: 9000
    - name: minio-console
      port: 9001
  selector:
    app: minio

