# Source: feast/charts/feature-server/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: feast-0.19.3-feature-server
  namespace: feast
  labels:
    app: feature-server
    component: serving
    chart: feature-server-0.19.3
    release: feast-0.19.3
    heritage: Helm
type: Opaque
stringData:
  application-secret.yaml: ""

