apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kserve
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/aukeaai/mlops-playground.git
    targetRevision: HEAD
    path: kserve/upstream
  destination:
    server: https://kubernetes.default.svc
    namespace: kserve
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
