apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-pipelines
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/aukeaai/mlops-playground.git
    targetRevision: HEAD
    path: kubeflow/pipelines
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeflow
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
